language: node_js
node_js:
  - "12"
cache:
  yarn: true
service:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker run --name localstack -e SERVICES="s3,dynamodb,secretsmanager,sqs,logs,elasticsearch"
    -d -p 4567-4600:4567-4600 localstack/localstack
script:
  - yarn
  - yarn build
  - ln -s node_modules sample-app/node_modules
  - echo "Waiting for LocalStack to be Ready"; while :; do docker logs localstack 2>&1
    | grep Ready > /dev/null; e=$?; if [ $e -eq 0 ]; then break; fi; sleep 1; done
  - yarn test
after_success:
  - sonar-scanner
deploy:
  provider: script
  script: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc && yarn run lerna:publish from-git --yes'
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: tcEB4EY08QosK+GT2auSoiD1khnJAgzTnzlhz9zQQ6ZsqXk36LIWVw0ZtqkkNlH1FHNQHnEY5rpHnvD8LNx3/3LZzIULibytfgeuDsyw215cQ3oeaYIYgTUizuD5TIQsqLkyxhQtuFQxMaLqaEF5Bho+x5Qsm8YaQlufsau+w4PJFxfvqioNbBuVT5niPvhlMpkIe+vsLxSGjm4t0xVoqpvAzThauan7ZJszTcHfMU1rqB83ZhEsgQexyRtadxB17I7tNTxP8kRQKAjUbuvYB09G9t6kX3U3sUNdU+/SqDZiIeIlExfKNT8zBtnjCGbSxfiFlq5ms4meQpXpbLYBT01IyspbZN5YPsPDgnkODMX4Fkc36b2R4XFRhEnzV0/uHkWnCNf7aRgporGhDVWQtX/Z/hV/+Jn387v5SXnCyJLdbiZjsnB9wqxyDHnl2BWYKFu8QGeSVw4X8f/89YfyyJTxPjUDGX8HwMXXK8pzggB2IzeSGEUuH0i+phQlryCUShFgw8c4hLvfb0Ec3f+ZyxKJ2k3OT5KTqwY8BlksJIZSOw/M/mQplhifBwZtZnW8+/wCrqKczIE4WF/lYqBhn5/tV2d9Y25K8IApxOnDIZTco3zTczuSwT6Tsu04zcMIOOBBdzgmwVn9kMb4CSM+1TNDh6+3JbHF7dm1I3qgBsY=
