language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - "node_modules"
service:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker run --name localstack -e SERVICES="s3,dynamodb,secretsmanager,sqs,logs,elasticsearch" -d -p 4567-4600:4567-4600 localstack/localstack
script:
  - yarn
  - yarn build
  - yarn webda-module
  - echo "Waiting for LocalStack to be Ready"; while :; do docker logs localstack 2>&1 | grep Ready > /dev/null; e=$?; if [ $e -eq 0 ]; then break; fi; sleep 1; done
  - yarn test
after_success:
  - sonar-scanner
deploy:
  provider: script
  script: "yarn run lerna:publish from-git"
  skip_cleanup: true
  tag: next
  on:
    tags: true
