name: "update docs"

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Set github
        run: git config --global user.email "automation@loopingz.com" && git config --global user.name "Loopingz Automation"

      - name: Build docs
        run: yarn run docs:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
