name: "update docs"

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build docs
        run: yarn run docs:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
