name: "Publish"

on:
  create:
    tags:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn run build

      - name: Publish project
        run: yarn run lerna:publish from-git --yes
